language: node_js
node_js:
  - 10.16.0
cache:
  directories:
  - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=$reporter_id
before_script:
  - export CC_TEST_REPORTER_ID=$reporter_id
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm install
  - npx jest -u --coverage
after_script:
  - ./cc-test-report after-build --exit-code $TRAVIS_TEST_RESULT
